- platform: rest
  resource: !secret esp_poele_temp
  name: "Ext. Temperature"
  value_template: '{{ float(value_json.temperature) }}'
  unit_of_measurement: "°C"
  scan_interval: 300
#- platform: yr
- platform: onewire
  names:
      28-80000003e85b: "Int."
  scan_interval: 300
- platform: yweather
  woeid: 12724400
  forecast: 0
  name: yw_day0
  monitored_conditions:
    - weather
    - temp_min
    - temp_max
- platform: yweather
  woeid: 12724400
  forecast: 1
  name: yw_day1
  monitored_conditions:
    - weather
    - temp_min  
    - temp_max
- platform: darksky
  api_key: ea0f9adbb1b6e010b7c1ae76543334e3
  forecast: [1,2]
  monitored_conditions:
    - summary
    - icon
    - temperature_max
    - temperature_min